---
output: html_document
---

<head>
<style>
table.table1, th.table1, td.table1 {
  border: 1px solid black;
}
tr.table1 {
  border: 1px solid black;
}
th.table1 {
  border: 1px solid black;
}
td.table1 {
  border: 1px solid black;
}
</style>
</head>

<b>Sodobna analiza podatkov</b>

To sosledje delavnic pobude DataScience@UL-FRI je namenjeno vsem, ki imajo v svojem poklicu opravka s podatki in bi se radi nau?ili, kako podatke urejati in jih analizirati na bolj sistemati?en in u?inkovit na?in. Z drugimi besedami tistim, ki bi radi postali analitik na svojem podro?ju dela. Preko spoznavnega nivoja so delavnice dostopne tudi udele?encem, ki ?e nimajo izku?enj s programiranjem.

Delavnice izvajamo v skladu s povpra?evanjem, a vsako delavnico predvidoma izvedemo vsaj enkrat letno, delavnice spoznavnega in osnovnega nivoja pa ve?krat letno.



<table class = "table1", style="width:100%">
  <tr class = "table1">
    <td class = "table1">Firstname</td>
    <td class = "table1"> <b>R ZA NEPROGRAMERJE</b> <br> R je programski jezik, ki je prilagojen delu s podatki in je najbolj popularen jezik med tistimi, ki se ukvarjajo s statisti?no analizo podatkov. Je tudi relativno preprost za uporabo in primeren za u?enje tudi brez predhodnih programerskih znanj. R nam omogo?a, da s podatki delamo samostojno, sistemati?no in brez omejitev, ki jih prinese uporaba bolj specifi?nih orodij, kot sta npr. Microsoft Excel in SPSS. Delavnico tipi?no izvedemo v obliki osmih 90-minutnih interaktivnih sre?anj z doma?imi nalogami. Udele?enci so na koncu sposobni programsko prebrati in shraniti datoteke s podatki, izvajati operacije nad podatkovnimi razpredelnicami in prikazati rezultate s preprostimi vizualizacijami.</td>
  </tr>
  <tr class = "table1">
    <td class = "table1">Jill</td>
    <td>Osnovni nivo je sestavljen iz treh intenzivnih delavnic, ki jih lahko obi??emo v poljubnem vrstnem redu. V njih pokrijemo snov, ki jo smatramo kot klju?no za strokovno delo s podatki, ne glede na to, s katerim podro?jem se ukvarjamo. Poudarek je na osnovnih konceptih, a sproti spoznamo tudi, kako operacije izvesti v praksi z uporabo programskega jezika R. Vsako delavnico tipi?no izvedemo v obliki ?tirih 90-minutnih sre?anj z nalogami za samostojno utrjevanje pred in po vsakem sre?anju. Delavnice so primerne za udele?ence, ki so ?e doma?i v programskem jeziku R ali ve??i programiranja v nekem drugem programskem jeziku.<br><br>
    <table style="width:100%">
      <tr>
        <th>UREJANJE PODATKOV</th>
        <th>POVZEMANJE IN VIZUALIZACIJA</th>
        <th>RAZUMEVANJE NEGOTOVOSTI</th>
      </tr>
      <tr>
        <td>Paketi tidyverse in dobre prakse dela s podatki. Branje in pisanje podatkov v standardnih oblikah (.csv, .xlsx, binarno). Izvajanje operacij nad vrsticami, stolpci in celicami tabel ter med ve?imi tabelami hkrati. Delo z nizi, kategori?nimi podatki, ordinalnimi podatki in datumi.</td>
        <td>Povzemanje numeri?nih, kategori?nih in ve?razse?nih podatkov. Tipi statisti?nih grafov, kako izbirati med njimi in kdaj je bolje uporabiti tabelo ali besedilo. Razumevanje kognitivne obremenitve bralca in vloge, ki jo pri tem igrajo besedilo, oblike, barve in prazen prostor.</td>
        <td>Prepoznavanje virov napak pri sklepanju o procesu, ki nas zanima, na podlagi podatkov. Sodoben pristop k ocenjevanju negotovosti z metodo bootstrap. Ocenjevanje in prikazovanje negotovosti v tabelah in grafih. Povezava z intervali zaupanja in testiranjem hipotez.</td>
      </tr>
    </table>
    </td>
  </tr>
  <tr>
    <td>Eve</td>
    <td>Jackson</td>
  </tr>
</table>